class MovieEngine(object):
    def __init__(self):
        self.movies = self.get_movie_info()

    def get_movie_info(self):
        return {'Perfect Strangers': ('Alex de la Iglesia',
                                      2017,
                                      'international',
                                      'comedy',
                                      'short'),
                'When Harry Met Sally': ('Rob Reiner',
                                         1989,
                                         'international',
                                         'comedy',
                                         'short'),
                'The Simpsons Movie': ('David Silverman',
                                       2007,
                                       'international',
                                       'comedy',
                                       'short'),
                'Annie Hall': ('Woody Allen', 1977, 'international', 'comedy', 'short'),
                'El futbol o yo': ('Marcos Carnevale', 2017, 'argentina', 'comedy', 'short'),
                'Baneros III todopoderosos': ('Rodolfo Ledo',
                                              2006,
                                              'argentina',
                                              'comedy',
                                              'short'),
                '100 veces no debo': ('Alejandro Doria',
                                      1990,
                                      'argentina',
                                      'comedy',
                                      'short'),
                'Esperando la carroza': ('Alejandro Doria',
                                         1985,
                                         'argentina',
                                         'comedy',
                                         'short'),
                'Parasite': ('Bong Joon-Ho', 2019, 'international', 'comedy', 'medium'),
                'Anything Else': ('Woody Allen', 2003, 'international', 'comedy', 'medium'),
                'The Truman Show': ('Peter Wair', 1998, 'international', 'comedy', 'medium'),
                'Hannah and her sisters': ('Woody Allen',
                                           1986,
                                           'international',
                                           'comedy',
                                           'medium'),
                'Relatos Salvajes': ('Damian Szifron', 2014, 'argentina', 'comedy', 'medium'),
                'Papa es un idolo': ('Juan Jose Jusid',
                                     2000,
                                     'argentina',
                                     'comedy',
                                     'medium'),
                'Enfermero de dia, camarero de noche': ('Anibal di Salvo',
                                                        1990,
                                                        'argentina',
                                                        'comedy',
                                                        'medium'),
                'El profesor patagonico': ('Fernando Ayala',
                                           1970,
                                           'argentina',
                                           'comedy',
                                           'medium'),
                'The Wolf of Wall Street': ('Martin Scorsese',
                                            2013,
                                            'international',
                                            'comedy',
                                            'long'),
                'Love Actually': ('Richard Curtis', 2003, 'international', 'comedy', 'long'),
                'Forrest Gump': ('Robert Zemeckis', 1994, 'international', 'comedy', 'long'),
                'The World According to Garp': ('George Roy Hill',
                                                1982,
                                                'international',
                                                'comedy',
                                                'long'),
                'Igualita a mi': ('Diego Kaplan', 2010, 'argentina', 'comedy', 'long'),
                'Nueve reinas': ('Fabian Bielinsky', 2000, 'argentina', 'comedy', 'long'),
                'Drive': ('Nicholas Winding Refn', 2011, 'international', 'crime', 'short'),
                'American Psycho': ('Mary Harron', 2000, 'international', 'crime', 'short'),
                'Reservoir Dogs': ('Quentin Tarantino',
                                   1992,
                                   'international',
                                   'crime',
                                   'short'),
                'Blood Simple': ('Joel Coen', 1984, 'international', 'crime', 'short'),
                'Muerte en Buenos Aires': ('Natalia Meta',
                                           2014,
                                           'argentina',
                                           'crime',
                                           'short'),
                'Tiempo de valientes': ('Damian Szifron',
                                        2005,
                                        'argentina',
                                        'crime',
                                        'short'),
                'El caso de Maria Soledad': ('Hector Olivera',
                                             1993,
                                             'argentina',
                                             'crime',
                                             'short'),
                'Ultimos dias de la victima': ('Adolfo Aristarain',
                                               1982,
                                               'argentina',
                                               'crime',
                                               'short'),
                'The Mule': ('Clint Eastwood', 2018, 'international', 'crime', 'medium'),
                'Catch me if you can': ('Steven Spielberg',
                                        2002,
                                        'international',
                                        'crime',
                                        'medium'),
                'Leon: The Professional': ('Leon Besson',
                                           1994,
                                           'international',
                                           'crime',
                                           'medium'),
                'Blow Out': ('Brian de Palma', 1981, 'international', 'crime', 'medium'),
                'The Irishman': ('Martin Scorsese', 2019, 'international', 'crime', 'long'),
                'The departed': ('Martin Scorsese', 2006, 'international', 'crime', 'long'),
                'Pulp Fiction': ('Quentin Tarantino', 1994, 'international', 'crime', 'long'),
                'The Godfather': ('Francis Ford Coppola',
                                  1972,
                                  'international',
                                  'crime',
                                  'long'),
                'The Boy': ('William Brent Eln', 2016, 'international', 'horror', 'short'),
                'House of 1000 Corpses': ('Rob Zombie',
                                          2003,
                                          'international',
                                          'horror',
                                          'short'),
                'The Blair Witch Project': ('Daniel Myrick',
                                            1998,
                                            'international',
                                            'horror',
                                            'short'),
                'A Nightmare on Elm Street': ('Wes Craven',
                                              1984,
                                              'international',
                                              'horror',
                                              'short'),
                'Juan de los Muertos': ('Alejandro Brugues',
                                        2011,
                                        'argentina',
                                        'horror',
                                        'short'),
                'El Nino de Barro': ('Jorge Algora', 2007, 'argentina', 'horror', 'short'),
                'Split': (' M. Night Shyamalan', 2016, 'international', 'horror', 'medium'),
                'Saw': ('James Wan', 2004, 'international', 'horror', 'medium'),
                'Scream': ('Wes Craven', 1996, 'international', 'horror', 'medium'),
                'The thing': ('John Carpenter', 1982, 'international', 'horror', 'medium'),
                'The House That Jack Built': ('Lars von Trier',
                                              2018,
                                              'international',
                                              'horror',
                                              'long'),
                'Orphan': ('Jaume Collet-Serra', 2008, 'international', 'horror', 'long'),
                'Thesis': ('Alejandro Amenabar', 1996, 'international', 'horror', 'long'),
                'The Shinning': ('Stanley Kubrick', 1980, 'international', 'horror', 'long'),
                'Coherence': ('James Ward Byrkit',
                              2013,
                              'international',
                              'science fiction',
                              'short'),
                'The Butterfly Effect': ('Eric Bress',
                                         2004,
                                         'international',
                                         'science fiction',
                                         'short'),
                'The Iron Giant': ('Brad Bird',
                                   1998,
                                   'international',
                                   'science fiction',
                                   'short'),
                'The Fly': ('David Cronenberg',
                            1984,
                            'international',
                            'science fiction',
                            'short'),
                'Fase 7': ('Nicolas Goldbart', 2010, 'argentina', 'science fiction', 'short'),
                'Ready Player One': ('Steven Spielberg',
                                     2018,
                                     'international',
                                     'science fiction',
                                     'medium'),
                'Eternal Sunshine of the Spotless Mind': ('Michael Gondry',
                                                          2004,
                                                          'international',
                                                          'science fiction',
                                                          'medium'),
                'The Matrix': ('Lilly Wachowski',
                               1998,
                               'international',
                               'science fiction',
                               'medium'),
                'The Swarm': ('Irwin Allen',
                              1978,
                              'international',
                              'science fiction',
                              'medium'),
                'Interstellar': ('Christopher Nolan',
                                 2014,
                                 'international',
                                 'science fiction',
                                 'long'),
                'Avatar': ('James Cameron', 2008, 'international', 'science fiction', 'long'),
                'Terminator 2: Judgment Day': ('James Cameron',
                                               1996,
                                               'international',
                                               'science fiction',
                                               'long'),
                'E.T. the Extra-Terrestrial': ('Steven Spielberg',
                                               1982,
                                               'international',
                                               'science fiction',
                                               'long')}

    def get_movie(self, range, genre, length, country):
        rating = 0
        movie = None
        for name, info in self.movies.items():
            count = 0
            if (info[1] in range):
                count += 1
            if (info[2] == country):
                count += 1
            if (info[3] == genre):
                count += 1
            if (info[4] == length):
                count += 1
            if (count > rating):
                rating = count
                movie = name + ' (' + str(info[1]) + ") " + info[0]

        return movie
